// <auto-generated />
using System;
using DojoActivityCenter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DojoActivityCenter.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190923013900_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DojoActivityCenter.Models.Join", b =>
                {
                    b.Property<int>("JoinId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlanId");

                    b.Property<int>("UserId");

                    b.HasKey("JoinId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Joins");
                });

            modelBuilder.Entity("DojoActivityCenter.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DurationTime")
                        .IsRequired();

                    b.Property<string>("PlanDescription")
                        .IsRequired();

                    b.Property<int>("PlanDuration");

                    b.Property<DateTime>("PlanStart");

                    b.Property<string>("PlanTitle")
                        .IsRequired();

                    b.Property<int>("PlannerId");

                    b.HasKey("PlanId");

                    b.HasIndex("PlannerId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("DojoActivityCenter.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DojoActivityCenter.Models.Join", b =>
                {
                    b.HasOne("DojoActivityCenter.Models.Plan", "JoinedPlan")
                        .WithMany("Attendees")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DojoActivityCenter.Models.User", "Joiner")
                        .WithMany("PlannedAttendees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DojoActivityCenter.Models.Plan", b =>
                {
                    b.HasOne("DojoActivityCenter.Models.User", "Planner")
                        .WithMany("PlannedPlans")
                        .HasForeignKey("PlannerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
